repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=150"
          - "--ignore=E203, E266, E501, W503, F403"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=25000"]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ci/multidoc-after.yaml # check-yaml fails on multi-doc
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: sort-simple-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/kynan/nbstripout # removes outputs to prevent commit conflicts
  #   rev: 0.6.1  # Use the latest version
  #   hooks:
  #     - id: nbstripout
